### ISSUE TITLE
Callback function on release

### ISSUE THREAD

**Issue by calvinzhe** [fseehawer/react-circular-slider#102]
Instead of calling a function for onChange whenever the value is changed, is it possible to call a function only when the slider is released?

I want to use this to communicate with hardware, but the hardware does not work well if it receives too many instructions rapidly.

**Comment by fseehawer** [comment]
No, but you could create a local variable, such as isMouseDown, that tracks whether the mouse is pressed (true) or not (false). This variable would prevent the callback function from calling your method continuously. Instead, the method would only be called with the final state of the slider when the mouse is released.

**Comment by calvinzhe** [comment]
Thanks.  I was able to use onMouseUp for the containing <div></div> to call a handler that applies the command.
