### ISSUE TITLE
Disable Interactive

### ISSUE THREAD

**Issue by shelbyt** [fseehawer/react-circular-slider#11]
Is it possible to use this as a non-interactive static "progress bar"?
I'd like to use this to  display "10 tickets remaining" 

I got half way there by overriding the knob color to be the same as progressColorFrom but the icon is still clickable/draggable. Thanks!

**Comment by fseehawer** [comment]
I just added two new props called hideKnob and knobDraggable. You can set knobDraggable to false if you don't want the knob to be rendered at all (there will be no interactivity) or just hide the knob by setting hideKnob to true (still draggable but the knob is hidden). Hope this helps and thanks for your feedback.
