### ISSUE TITLE
Semi-circular slider (help wanted)

### ISSUE THREAD

**Issue by ShimantaBhuyan** [fseehawer/react-circular-slider#12]
Can we create a semi-circular slider instead of the circular slider?
Please help.

**Comment by fseehawer** [comment]
I have a feature on my to-do list where you can set the degrees of the slider. 360° will be default and if you set it to 180° you get a half circular slider. I might get it done in a week or so.

**Comment by ShimantaBhuyan** [comment]
That would be perfect!

**Comment by fseehawer** [comment]
After thinking about the implementation I have come to the conclusion not to implement this feature. At least not until I have a nicer solution for some props that will not work in a semi circular slider.
