### ISSUE TITLE
Knob disappears when width less than 150

### ISSUE THREAD

**Issue by uvdoctor** [fseehawer/react-circular-slider#13]
Would like to have slider width of 120 for one of the components, but knob doesn't appear at all for any width less than 150 of the slider.

**Comment by fseehawer** [comment]
Works fine for me. Maybe you can share your implementation?

**Comment by uvdoctor** [comment]
Apologies, I have realized that knob doesn't disappear but is displayed at wrong position.

When page is rebuilt after width related code change, the knob position doesn't move & hence knob is disconnected from the track. If entire page is refreshed, then the knob shows up properly.

**Comment by fseehawer** [comment]
Can you show me what props you used and how you set them?
e.g.:
<CircularSlider
    min={0}
    max={360}
    direction={-1}
    knobPosition="right"
    appendToValue="°"
    valueFontSize="4rem"
/>

**Comment by uvdoctor** [comment]
Apologies for the delay. Here are the props:

<CircularSlider onChange={(val: string) => props.changeHandler(props.float ? parseFloat(val) : parseInt(val))}
                label={props.label} trackColor="#edf2f7" data={props.data} dataIndex={(props.value - getVal(props.data[0])) / props.step}
                appendToValue={props.unit} width={props.width} labelColor="#4a5568" labelBottom={props.labelBottom}
                valueFontSize="1.5rem" labelFontSize="1.5rem" progressColorFrom={props.colorFrom ? props.colorFrom : "#48bb78"} 
                progressColorTo={props.colorTo ? props.colorTo : "#48bb78"} knobColor="#cbd5e0" />

**Comment by uvdoctor** [comment]
I have wrapped this into a component for resuse across project. Width of 120 is working after refreshing the page as knob shows up in different position after page is reloaded upon code change.

**Comment by fseehawer** [comment]
Is it a hot reloading issue while you are developing or does the issue occur also on a production build?

**Comment by uvdoctor** [comment]
Hot reloading issue. Haven't seen this in production yet.

**Comment by fseehawer** [comment]
This will be an issue similar to https://github.com/reduxjs/redux/issues/1940

**Comment by fseehawer** [comment]
I will have to check and see if I can implement a fix for it
