### ISSUE TITLE
Knob animation not working

### ISSUE THREAD

**Issue by uvdoctor** [fseehawer/react-circular-slider#15]
I am using SSR with Next. For some reason, knob related animation doesn't work.

Thanks for your help!

**Comment by fseehawer** [comment]
The global CSS isn't loaded in the next environment so you are missing the pulse CSS animation.

@keyframes pulse {
	0% {
		transform: scale(1);
	}
	50% {
		transform: scale(0.8);
	}
	100% {
		transform: scale(1);
	}
}

**Comment by fseehawer** [comment]
`body {
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen",
    "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue",
    sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

code, pre {
  font-family: source-code-pro, Menlo, Monaco, Consolas, "Courier New",
    monospace;
}

pre {
  display: block;
  white-space: pre-wrap;
  color: #272b77;
}`

**Comment by uvdoctor** [comment]
Thanks, I have copied the keyframe animation in my app's index.css. Its working fine.
