### ISSUE TITLE
import issue

### ISSUE THREAD

**Issue by kiranb555** [fseehawer/react-circular-slider#16]
when trying to import, ` import CircularSlider from "@fseehawer/react-circular-slider";`
throws the error : Uncaught TypeError: Object(...) is not a function
    at N (static/js/bundle.js:1515).
i am using react version 16.2

**Comment by fseehawer** [comment]
16.2.0 (November 28, 2017) is quite an old version. Maybe you can update react and try again?

**Comment by kiranb555** [comment]
it's worked fine with my windows system, with few warnings like below. But above error occuring only in my Ubuntu system. 

![Untitled](https://user-images.githubusercontent.com/43150185/84830521-20f03080-b047-11ea-8d21-7adae1f3db92.png)

**Comment by fseehawer** [comment]
I would recommend updating packages to the latest versions.

**Comment by kiranb555** [comment]
Thank you
