### ISSUE TITLE
Progress Color From & To don't get rendered on dynamic conditions

### ISSUE THREAD

**Issue by uvdoctor** [fseehawer/react-circular-slider#17]
I have wrapped this in a react component so that it can be reused across various forms. Need to change progressColorTo dynamically based on a condition as shown below. However, though condition is true, red color doesn't get rendered.

<CircularSlider onChange={(val: string) => props.changeHandler(props.float ? parseFloat(val) : parseInt(val))}
                label={props.label} trackColor="#edf2f7" data={props.data} dataIndex={(props.value - getVal(props.data[0])) / props.step}
                appendToValue={props.unit} width={props.width} labelColor="#4a5568" labelBottom={props.labelBottom}
                valueFontSize="1.5rem" labelFontSize="1.5rem" progressColorFrom="#48bb78"
                progressColorTo={props.changeColor ? "#FF0000" : "#48bb78"} knobColor="#cbd5e0" />

**Comment by fseehawer** [comment]
Hi, please check if the prop is changing. I just created a codesandbox and it works: https://codesandbox.io/s/suspicious-antonelli-mb25h

**Comment by uvdoctor** [comment]
Thanks, its working for me as well now.
