### ISSUE TITLE
Progress position won't change with knob position

### ISSUE THREAD

**Issue by vibecode** [fseehawer/react-circular-slider#2]
1. I don't know if this is by design but if you set knob position other than top, the progress bar still starts from the top. This is counterintuitive, as I expect the 0 value on the track to be the same as the initial knob position.

2. More like some features request: would be nice if the endless scrolling be optional. Now I have a game-like application where users enter values from a slider on mouseup and they could get 0 trying to enter 100% easily. Also would be great if there was an option to move label position underneath the value.

**Comment by fseehawer** [comment]
Hey, thanks for reaching out. All of the points you mentioned are very valid and hav also been featured I wanted to implement. I think I will be working on all of them in the very near future. 

Thanks for your feedback and happy holidays!

Von meinem iPhone gesendet

**Comment by fseehawer** [comment]
@vibecode With the latest release point (1.) from your list was fixed. The top label can now also be positioned underneath the value by using the labelBottom prop (checkout the examples).

**Comment by vibecode** [comment]
Great, thanks!
