### ISSUE TITLE
Keyboard events

### ISSUE THREAD

**Issue by uvdoctor** [fseehawer/react-circular-slider#20]
Hello,

Please advise on how to handle 'Enter' key and also change slider value through keyboard. Couldn't find these in documentation.

Best regards,
Umang

**Comment by fseehawer** [comment]
Hi, it is not clear what you are trying to do; however, you could use the "dataIndex" prop to the position of the knob, so you could have key events just changing the prop depending on your use case. Here is a simple example with the arrow keys (you need to focus the window before hitting the arrow keys):

https://codesandbox.io/s/interesting-poincare-lx66w

**Comment by uvdoctor** [comment]
Apologies for the late response. Will definitely try it out and get back to
you.
