### ISSUE TITLE
Advice needed regarding the onChange prop

### ISSUE THREAD

**Issue by Vixan** [fseehawer/react-circular-slider#24]
Greetings,

I really like this slider implementation, so I have decided to try to use it as a circular audio seek control for a music player. 
What I have noticed is that when `dataIndex` changes, the function passed to the `onChange` prop will get called. In my case, this means that the music player will constantly "seek" the time of the audio, which causes a stutter and it's just incorrect for this use case.

I'm not sure how to handle this, so I decided to just ask for an advice. I have also created a [CodeSandbox link here](https://codesandbox.io/s/admiring-heisenberg-cgxl2?file=/src/App.js) to illustrate how I'm trying to use this circular slider.

Thank you in advance for any help.

**Comment by fseehawer** [comment]
Hi @Vixan, it's a bit tricky for your use case. I will add a new prop to handle cases like yours by the end of next week. Anyway, I updated your codesandbox with a simple workaround for now. Thanks for the feedback!

**Comment by Vixan** [comment]
Thank you very much, @fseehawer. 
It helps a lot 🙂 and I will close this issue then.
