### ISSUE TITLE
Is it possible to use two knobs at the same time?

### ISSUE THREAD

**Issue by BrandonEscamilla** [fseehawer/react-circular-slider#25]
I am working on a project where I am using this library, but I need the possibility to use two knobs at the same time over the same slider, so I am wondering if it is possible with the current status of this library. 

If not,  I am willing to contribute to this library, but I am wondering what changes need to be made to make this possible. If that's ok for you and of course if it's on the roadmap of this project.

If you are ok with this I would appreciate some hints of where to start. 👨‍💻

**Comment by fseehawer** [comment]
Hi @BrandonEscamilla, currently it isn't possible. I was planing to work on the feature soon, but you are welcome to create a PR for it.

**Comment by BrandonEscamilla** [comment]
We ended using just 1 knob, thank you for the time! 😄
