### ISSUE TITLE
Slider Knob out of position

### ISSUE THREAD

**Issue by kiranb555** [fseehawer/react-circular-slider#26]
Hi, I am getting an issues like below only in production react app.  have attached code and output below. please let me know any issues you can identify.

![tuners](https://user-images.githubusercontent.com/43150185/108346345-49977e00-7205-11eb-9e1f-dd644975a9ed.png)

 `<CircularSlider
                      label={"test"}
                      labelFontSize="0"
                      valueFontSize="1.5em"
                      knobSize={10}
                      labelColor="#3c548e"
                      knobColor="#3c548e"
                      progressColorFrom="#3bcbe3"
                      progressColorTo="#3bcbe8"
                      verticalOffset="-0.018em"
                      progressSize={14}
                      trackColor="#eeeeee"
                      trackSize={14}
                      min={0}
                      data={Array.from({ length: 101 }, (v, k) => k + "%")}
                      dataIndex={volatality}
                      onChange={(value) =>
                        sliderHandler({ value, type: volatility_type })
                      }
                      width={100}
                      height={100}
        />`

**Comment by fseehawer** [comment]
Hi, as long as you don't go below the track size, the position of the knob should be fine: https://codesandbox.io/s/keen-wozniak-5fgt6

**Comment by kiranb555** [comment]
Thank you @fseehawer
