### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by santalvarez** [fseehawer/react-circular-slider#3]
Hi im getting this error when i run my app. I imported the component like this:
const CircularSlider = require('@fseehawer/react-circular-slider');
I cant seem to find a way to solve this issue. Do you know if this has happened before?
Thanks.

**Comment by fseehawer** [comment]
window is not defined sounds like a server error. Is your app using server side rendering? I use the window object to device and mouse position things that don't exist on the server.

**Comment by santalvarez** [comment]
Yeah i use SSR. Thanks for the help, do you have an idea of how to mock that stuff to make the slider work?

**Comment by fseehawer** [comment]
I just updated the slider with a simple mock for window and document.

**Comment by santalvarez** [comment]
Thanks for the update. I tried it and im getting:
 `Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object`
I'm guessing it has to do with my project, did you try it with the new update?

**Comment by fseehawer** [comment]
I haven't tried SSR with the slider yet. Do you get any errors when not importing the slider?

**Comment by santalvarez** [comment]
No i don't get any without it.

**Comment by fseehawer** [comment]
which react version are you using?

**Comment by santalvarez** [comment]
16.8.6

**Comment by fseehawer** [comment]
I will make the slider SSR compatible and come up with an update soon. Sorry for any inconvenience.

**Comment by santalvarez** [comment]
No problem dude. The fact that you were willing to update the code and do it so quicky is awesome. Thanks a lot.

**Comment by fseehawer** [comment]
I'm back actively working on some features and SSR is quite high on the priority list.

**Comment by oyeanuj** [comment]
+1 for SSR support!

**Comment by uvdoctor** [comment]
Hi, thanks for your awesome work! I just downloaded the latest version and am getting this error. My app is using SSR with Next. Please advise.

**Comment by fseehawer** [comment]
Hi, I haven’t tried using the slider with next yet, but I have used it in SSR so might be a problem specific to next. I will need to test it myself and see exactly where the problem is. I’ll definitely take it to my to-do list. Thanks for the feedback!

**Comment by uvdoctor** [comment]
Thanks a lot Fidel for your help and prompt response!

**Comment by uvdoctor** [comment]
Hi Fidel,

Just following up on this issue. Did you get a chance to try with Next?
Would love to use your component if possible.

Best regards,
Umang

**Comment by fseehawer** [comment]
Hello Umang,

Yes, I'm just about to fix the issue. However, if you like you can use the current version as follows in your next.js project.

`import dynamic from 'next/dynamic'

const CircularSlider = dynamic(
    () => import('@fseehawer/react-circular-slider'),
    { ssr: false }
)`

Best,
Fidel

**Comment by fseehawer** [comment]
The issue was fixed in version 2.3.1

**Comment by uvdoctor** [comment]
Thanks Fidel for the suggestion. Looking forward to the fix.

Best regards,
Umang

**Comment by uvdoctor** [comment]
Thanks a lot Fidel! It is working now.
