### ISSUE TITLE
Support for multiple rounds/cycles to complete one percentage

### ISSUE THREAD

**Issue by samawiamoin** [fseehawer/react-circular-slider#31]
I need a functionality in which there is a maximum value of 100 and I want the user to slide the whole circle 3 times to complete the maximum value. 

For example: Maximum value 100 will be divided into 3 parts equally 
1. 0 - 33.3%
2. 33.3% - 66.6%
3. 66.6% - 100%

Is it possible to achieve this functionality using this package?

**Comment by fseehawer** [comment]
In the current implementation, any values given are evenly spaced out in 360 degrees only.

**Comment by samawiamoin** [comment]
@fseehawer Thanks for replying 

If we provide 100 as a maximum value it just change the label to be evenly distributed in 100?

**Comment by fseehawer** [comment]
Yes, there are two ways to provide values that are evenly distributed in 360 degrees. First by giving min, and max values. See this example: https://codesandbox.io/s/exciting-star-gd4p8 and the second way is to create an array of strings. See the "Alphabet" example on http://localhost:3000/react-circular-slider.

**Comment by samawiamoin** [comment]
Is there a way that we can repeat to load this component three times with update min and max to complete 100 percent?

**Comment by fseehawer** [comment]
Do you mean one component doing 3 x 360 degrees where the value is from 0 to 100? If so no. If you mean three different component, yes: https://codesandbox.io/s/exciting-star-gd4p8

**Comment by samawiamoin** [comment]
Thanks. Another thing, I am trying to set state variables in OnChange method of Circular Slider but the state variables are not setting in there. 

Do you know any way to maintain setstate in OnChange method of Circular slider?

**Comment by fseehawer** [comment]
You can set the state using onchange prop. See example: https://codesandbox.io/s/exciting-star-gd4p8

**Comment by samawiamoin** [comment]
Can we pass a method in onChange prop? like: 
`onChange={ (value: any) => {
           setMax();
           setMin();
}}`

Its not setting state like this

**Comment by fseehawer** [comment]
Yes, you can: https://codesandbox.io/s/exciting-star-gd4p8

**Comment by kinhdev24** [comment]
Hi @fseehawer , 
Is there any way to set a cycle to 180 degrees instead of 360?
