### ISSUE TITLE
Support for disabling rotation is some direction

### ISSUE THREAD

**Issue by DarkZett** [fseehawer/react-circular-slider#32]
Is there any way to disable rotation in some direction like clockwise or anticlockwise?
I've checked the documentation, but haven't found the needed option...

**Comment by fseehawer** [comment]
What is the use case? What if the user wants to set some value and overshoots? He can't rotate back to a lower value?

**Comment by DarkZett** [comment]
Yep, that exactly what I need
Only moving to one side without the possibility to turn back
The use case is that I'm using the slider for schematic twisting the rod on the wound and I need disable ability to moving back

**Comment by fseehawer** [comment]
Sorry, that isn't a use case that I have considered. I will add the idea to my to-do list. Thanks!

**Comment by DarkZett** [comment]
@fseehawer by the way, making the component controllable with some value property would help with my issue, as well as it adds a bit more options fr customization at all

**Comment by fseehawer** [comment]
You can set the value by using the dataIndex prop. Check this example: https://codesandbox.io/s/friendly-nash-4enzg
