### ISSUE TITLE
Component Exception  Error Message

### ISSUE THREAD

**Issue by Salvasgdo** [fseehawer/react-circular-slider#33]
![WhatsApp Image 2021-07-14 at 13 39 43](https://user-images.githubusercontent.com/28058640/125675185-31ab7a47-39f8-40cd-9b66-5fa5be555f2d.jpeg)

![Captura de pantalla de 2021-07-14 13-41-14](https://user-images.githubusercontent.com/28058640/125675356-28c3743e-b025-41dc-a6d0-e30adf2d89cb.png)

I want to use the component, but I have an error. The error is that I need a Text component and i dont know why . 
Any help??

**Comment by fseehawer** [comment]
The package is made for react and probably won't work in a react native project. But there will be other packages for react native.

**Comment by Salvasgdo** [comment]
Oh, I see. I didnt see that. Thank you. !!
