### ISSUE TITLE
Knob doesn't start at the top

### ISSUE THREAD

**Issue by thisismygatekeeper** [fseehawer/react-circular-slider#47]
I was trying this set up
```
<CircularSlider
  label="Test"
  labelColor="white"
  progressSize={0}
  trackSize={16}
  knobSize={48}
  knobColor={"#3AFAEF"}
  knobPosition="top"
  data={[0, 1, 2]}
  dataIndex={0}
/>
```
But the initial position of the knob is like this

<img width="333" alt="Screen Shot 2022-02-23 at 11 03 45 AM" src="https://user-images.githubusercontent.com/96497730/155389367-7967101f-4bb4-45a3-85d4-409779cf4036.png">

Is there any way we can make the knob starts at the exact top? Thank you!

**Comment by fseehawer** [comment]
That's because the three options (0, 1, 2) are spread to 360 degrees and the knob positioned in the middle of each option. Currently, there is no prop to position the knob at the beginning, middle or end of each section.

**Comment by Janvampierssel** [comment]
There is a way to set it at the top!

With `dataIndex={}` you can adjust the value until it visually initiates at the start.

For my 10-step slider I need to set it to `dataIndex={-0.49}` for it to be (almost) exactly at the top.
