### ISSUE TITLE
Issues with slider being cropped 

### ISSUE THREAD

**Issue by Rahul-Vig** [fseehawer/react-circular-slider#5]
![example](https://user-images.githubusercontent.com/37634070/71383483-999b9600-25aa-11ea-833f-bd469499fde5.png)

For some reason no matter what I try to change the slider is constantly cropped

**Comment by fseehawer** [comment]
The container or any of the parent elements in which the slider is embedded probably has the css property overflow hidden. If you send me a staging link I will gladly point out exactly where. Hope this helps.

**Comment by fseehawer** [comment]
The latest version will keep the track path within the sliders with.
