### ISSUE TITLE
Set Value of Slider from Code or React State Variable

### ISSUE THREAD

**Issue by Tigge11** [fseehawer/react-circular-slider#57]
Hey,
is it possible to set the Value of the Knob to be a State Variable in React?
Or are there any options to set the Value of the Knob after render, except for changing it in the UI? Because I want to implement a Text Field below the Slider that can be changed and changes the Slider.

**Comment by fseehawer** [comment]
Hi Tigge11, yes, If I understand you correct, you can do something like this: https://codesandbox.io/s/loving-buck-pzx9nn. Hope this helps.

**Comment by Tigge11** [comment]
That's perfect.
Thanks for the quick response.

**Comment by Janvampierssel** [comment]
Hi, is there a way to do this in a slider that has continuous enabled?

When I try this solution in a continuous one it doesn't seem to work.
