### ISSUE TITLE
progressColor issue when label has >1 word

### ISSUE THREAD

**Issue by nwenhui** [fseehawer/react-circular-slider#6]
<CircularSlider
          label="target temperature"
          min={50}
          max={80}
          appendToValue="°F"
          labelColor="#005a58"
          knobColor="#005a58"
          progressColorFrom="#00bfbd"
          progressColorTo="#005a58"
          progressSize={24}
          trackColor="#eeeeee"
          trackSize={24}
        />

results in no progressColor showing

**Comment by fseehawer** [comment]
I have fixed the issue in the latest version. Thanks for your feedback!
