### ISSUE TITLE
Minimum value issue

### ISSUE THREAD

**Issue by charlesmooredev** [fseehawer/react-circular-slider#64]
I noticed that if you set the `min` value as something greater than 0 it seems to want to set the value as the maximum value and won't allow you to change the value anymore. 

In the screenshot I'm posting my `min` value is set to 1 and `max` value set to 20, and on load it sets the value to the maximum value and you cannot change it.

![circular issue](https://user-images.githubusercontent.com/37604197/199040199-6100b86f-7853-4d4e-b51a-db2cdaeb436c.png)

**Comment by fseehawer** [comment]
There is no step props, but you can use the data prop and pass any values sequence. I've updated the above example to demonstrate stepping through only even numbers.

**Comment by fseehawer** [comment]
You can always write a helper function to generate the values you wish to push to the data prop. Something like: 

`function everyNth(arr, nth) {
  const result = [];

  for (let i = 0; i < arr.length; i += nth) {
    result.push(arr[i]);
  }

  return result;
}

everyNth([1, 2, 3, 4, 5, 6], 2); // will return [1, 3, 5]

`

**Comment by charlesmooredev** [comment]
So the issue I'm having is that when passing an array into data if you don't start at 0 when you make a change, the onChange breaks
If you start at 0 it works

but then a minimum number doesn't work due to you have a starting point of 0 every time rather than setting a minimum starting point

[Here is the issue](https://codesandbox.io/s/elated-dust-sy5mfr?file=/src/App.js)

When messing with it you can see that it will automatically go to the max value

**Comment by fseehawer** [comment]
Maybe this will help? https://codesandbox.io/s/vigilant-bell-klgv6l

**Comment by charlesmooredev** [comment]
> Maybe this will help: https://codesandbox.io/s/vigilant-bell-klgv6l? Otherwise, please let me know what you are trying to do. You shouldn't be setting dataIndex onChange.

So from my understanding `dataIndex` is the initial placement of the slider handle right? So you would want the slider handle to be placed at the initial value of the slider, but from the way you describe it is that the dataIndex stays active even after a change occurs correct?

**Comment by fseehawer** [comment]
The default index is 0. So, you can use dataIndex to set to any index of the data array. In the code you shared there are multiple issues:
```
data={getStepValues}
dataIndex={value * 100}
```
Check the resulting array of getStepValues and setting the "value * 100" where on each render the "value" changes doesn't make sense to me. Maybe you can describe what you are trying to accomplish, then I may be able to help with an example.

**Comment by charlesmooredev** [comment]
So I have a setup with dial knobs that takes backend values and plugs into the circular-slider to have a default view of the correct placement of the given value on initial load, then after you make changes it will send that new value to the backend and be saved.

In the example I'm using `useState`, but outside of the example I'm pulling a value from the backend and plugging that in, so the dataIndex is setting that initial value to be what the backend value is set to

**Comment by charlesmooredev** [comment]
I added a fix to the `dataIndex` by checking for a change, and once the initial change has been made it will set it to a different value which seems to be a workaround of the setting of `value`

**Comment by fseehawer** [comment]
There should be no issue with that. So, if your BE response is backend_api_response. See https://codesandbox.io/s/vigilant-bell-klgv6l.
