### ISSUE TITLE
incorrect behavior if direction=-1 and value=0

### ISSUE THREAD

**Issue by SebDelile** [fseehawer/react-circular-slider#75]
Hi, thanks a lot for your amazing component !! I'm using it to manage image rotation.

Sadly, I recently run into an issue while implementing flipping feature. When I set the direction to -1 and the current value is 0 deg, it automatically goes to 180 deg. See this minimal example of the encountered issue : https://codesandbox.io/s/xenodochial-aj-n0blww?file=/src/App.js

if you slide to a random value, like 28 deg for example, everything is working just fine : flipping makes a miror symetry according to vertical axis, and +90 / -90 buttons adds or reduces the value by 90 deg whatever the slider is flipped or not.

However, if the value is 0 deg, it is automatically transformed into 180 deg if the slider is flipped.

I've tried to investigate a bit the source code but I didn't catch the bug yet. My current lead is that the data array is not correctly modified when the direction is negative, may be the fisrt value is no more 0 but the middle value of the original array ... 

I'll keep you posted if I found anything, anyway a big thanks if you have time to investigate :)

**Comment by SebDelile** [comment]
Ok I've deeply investigated and the issue seems to be related to `knobOffset` and the way it is used in `setKnobPosition`. if the props `knobPosition` is set to "right" (equal `offsetRadians=0`), there is no more issue. for any other position the issue appears.

```js
const knobOffset = {
    top: Math.PI / 2,
    right: 0,
    bottom: -Math.PI / 2,
    left: -Math.PI
};
```

**Comment by fseehawer** [comment]
Thanks for the support, really appreciate it.

**Comment by SebDelile** [comment]
You're welcome :) thanks for the quick review/merge ! 

When do you think the patched version will be available via the npm package ?

**Comment by SebDelile** [comment]
Amazing, so quick ! thanks again to you for this component, very useful :D
