### ISSUE TITLE
Missing value Prop in react-circular-slider Component

### ISSUE THREAD

**Issue by gheors** [fseehawer/react-circular-slider#80]
Problem:
The react-circular-slider component currently lacks the ability to utilize a value prop. While the component does offer the InitialValue prop for initializing the slider's starting value, it does not provide a mechanism for dynamically updating the slider's value as it is being used.

Expected Behavior:
In a comprehensive slider component like react-circular-slider, the ability to update the slider's value dynamically is crucial. By introducing a value prop alongside the existing InitialValue prop, developers can ensure that the slider's value reflects the user's interaction in real-time.

Use Case:
Imagine a scenario where the react-circular-slider component is used as a key input element for a data visualization tool. The user interacts with the slider to set a specific value, and this value needs to be passed to other components for further processing and visualization. Without a value prop, it becomes challenging to maintain a synchronized data flow, and the tool's accuracy could be compromised.

Proposed Solution:
To address this issue, it is recommended to introduce a value prop to the react-circular-slider component. This prop would serve as a two-way binding between the slider's value and the parent component's state. When the user interacts with the slider, the value prop would update accordingly, allowing the parent component to receive and propagate this value to other components as needed.

By implementing the value prop, the react-circular-slider component would provide a complete solution for dynamic interaction and data flow, making it more adaptable to various use cases and enhancing its overall utility.

**Comment by fseehawer** [comment]
First off, thank you for taking the time to write this detailed feature request! Your insight into the problem and the proposed solution is greatly appreciated.

I've noted your request and will be adding it to my to-do-list. Having said that, if you (or anyone else) have the bandwidth to start working on this improvement or any other features, please do create a PR. I'll be more than happy to review and, if all looks good, merge it in.

Thanks again for your contribution!
