### ISSUE TITLE
Show only manipulated value?

### ISSUE THREAD

**Issue by simenjh** [fseehawer/react-circular-slider#83]
I'm trying to create a slider to show sleep duration. I would like it to display say "8 hours, 3 minutes". It doesn't seem to be possible to change how the value is displayed. I can display the manipulated value in the label, but then I need to hide the value from the slider. There seems to be only hideLabelValue which hides both the label and the value...

Any suggestions or is this just not possible?

**Comment by fseehawer** [comment]
You can use any string as the value, so, that should be possible. Here is an example: https://codesandbox.io/s/restless-flower-vlsjvv. Please let me know what you are trying to accomplish so that I can give you a better example.

**Comment by simenjh** [comment]
I was too quick initally and thought renderLabelValue returned a function, so couldn't get it to work. I see now that it returns jsx. Got it working like I wanted to. Thanks!
