### ISSUE TITLE
Not able to use mouse on Ipad

### ISSUE THREAD

**Issue by tillganster** [fseehawer/react-circular-slider#84]
We are trying to use an external mouse on Ipad to control our app. This is not possible as you only apply touch events on Ipads.

We changed it locally and got it working. Are you interessed in a PR ?

**Comment by fseehawer** [comment]
Any contribution is warmly welcomed. Please create a PR for the update. Thanks!

**Comment by maxbaeuml** [comment]
Thanks for your help. It seems like everything is working. Issue can be closed!
