### ISSUE TITLE
Custom Track Design

### ISSUE THREAD

**Issue by catrawalkar** [fseehawer/react-circular-slider#85]
Hi, I can see I am able to add "svg" for knob's design.

I wish to have a custom Track Design as well (see image).

<img width="595" alt="Screenshot 2023-10-02 at 3 01 23 PM" src="https://github.com/fseehawer/react-circular-slider/assets/15074162/8ec69fec-9a7c-4750-9103-f7debe36a55b">

How can I achieve this type of slider? Any help would be very much appreciated.

**Comment by catrawalkar** [comment]
Also, can I set a custom start and end Angle for the circular slider just like - Apexcharts (https://apexcharts.com/docs/options/plotoptions/radialbar/)

**Comment by fseehawer** [comment]
Hi @catrawalkar, this is currently not possible. I will add to my to-do list. You will have to go to another library to achieve that. I can recommend https://echarts.apache.org/examples/en/editor.html?c=gauge-grade, but there are, as you mentioned, others too.

**Comment by catrawalkar** [comment]
But I need something with a slider. The one I mentioned, and even the one you mentioned is not draggable and cant be used as slider.

**Comment by catrawalkar** [comment]
Can you please recommend some other library? 

Could I get in touch with you for further discussing the development of custom component on a chargeable basis if you are willing to?
