### ISSUE TITLE
Custom value in the center

### ISSUE THREAD

**Issue by oyeanuj** [fseehawer/react-circular-slider#9]
Hi @fseehawer, thanks for creating this useful library! 

My use-case is that on completion (100), I'd like to show a checkmark rather than the label. So I'm wondering if you'd be open to the value in center to optionally being a function to which the progress can be passed? 

With a `renderLabelValue` being a function, it might also take care of `appendToLabel` and `prependToLabel` props, rather than the library supporting each of those cases specially.

Thoughts?

**Comment by fseehawer** [comment]
Hi @oyeanuj, thanks. You are always welcomed to contribute if you like and create a pull request for your feature. Otherwise, I will add it to my to-do list but might take a week or so to get it done.

**Comment by fseehawer** [comment]
I've just added a new renderLabelValue prop. You can render custom jsx code instead of the default labels. So now you can position, style and render anything.
